#!/bin/bash

# Kill running chains
killall desmosd
killall bitsongd

# Kill running LCD
killall desmoscli
killall bitsongcli

# Wipe the data
rm -r ~/.relayer
rm -r ./data

# Re-create the chains
echo y | ./scripts/two-chainz

# Make sure the chains are running
sleep 3

# Congiure the relayer
rly config init
rly cfg add-dir ./configs/demo/

rly keys restore ibc0 testkey "$(jq -r '.secret' data/ibc0/n0/desmoscli/key_seed.json)"
rly keys restore ibc1 testkey "$(jq -r '.secret' data/ibc1/n0/bitsongcli/key_seed.json)"

rly lite init ibc0 -f
rly lite init ibc1 -f

sleep 5

# Create the clients
rly tx link demo --timeout 3s -d
